name: Export URB-U-0005 images

on:
  pull_request:
    types: [synchronize]

jobs:
  export-urb-u-0005:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: urb-u-0005-images
          path: |
            sources/osobni-archiv-jaromira-urbanka/Rychvaldské větrné mlýny/P1010447.jpg
            sources/osobni-archiv-jaromira-urbanka/Rychvaldské větrné mlýny/P1010446.jpg
            sources/osobni-archiv-jaromira-urbanka/Rychvaldské větrné mlýny/P1010445.jpg
            sources/osobni-archiv-jaromira-urbanka/Rychvaldské větrné mlýny/větrný mlýn u hebdy/P1010447.JPG
            sources/osobni-archiv-jaromira-urbanka/Rychvaldské větrné mlýny/větrný mlýn u hebdy/P1010446.JPG
            sources/osobni-archiv-jaromira-urbanka/Rychvaldské větrné mlýny/větrný mlýn u hebdy/P1010445.JPG
          if-no-files-found: error
          retention-days: 1
